export const products = [
    {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Under Water Acoustic Communication Modem",
        "description": "Naval Ships' ATDS deploys decoys via LCP for torpedo defense. Ready for any situation.",
        "detailDescription" : "Data Communication in the dynamic subsea environment is a challenging task. To meet this requirement, we have designed and developed Under Water Acoustic Communication Modem, which provides half duplex communication. This under water telemetry is done in the form of acoustic signals which is achieved using acoustic sensors. The purpose of UACM to establish communication between the On shore Control Monitoring station and Off shore Mine laid in sea water. This communication system is to control the Data Acquisition System operations remotely from the surface vessel or from the shore. The UACM sends the digital data and which is converted to acoustic signal using the acoustic sensors. The acoustic sensor in the sea mine receives this data and then converts it back to the digital form. The UACM can be used for wireless data communication in shallow or deep water applications."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "DECOY Launcher (Anti Torpedo)",
        "description": "Our Naval Ships' Anti-Torpedo Defense System (ATDS) deploys decoys remotely via the Launch Control Panel (LCP). Ready for any situation.",
        "detailDescription" : "Anti-Torpedo Defense System (ATDS) installed Naval Ships is capable of firing the decoys for the purpose of detonating and distracting the incoming Torpedo.  The Launch Control Panel (LCP) installed on this system is designed and developed to remotely control the torpedo decoy launchers to fire the decoy so as to achieve the ATDS functionality. With different modes of firing options like Remote, Local and Emergency, the LCP provides the necessary operational requirements in unforeseen situations encountered by our Indian Navy."

    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Programmable Pinger Receiver (Under water Mines Recovery Aid)",
        "description": "Crafted for receiving acoustic pings from underwater mines, aiding localization and archiving.",
        "detailDescription" : `The Programmable Pinger Receiver Unit is an Acoustic Ping Receiver which is designed and developed for the purpose of receiving the pings generated by the acoustic sensor. With the help of this unit, it becomes easy for the Localization and archiving of the pings generated by Under Water Mines.`
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "LAN Based Data Acquisition Unit (Flight Data Recorder)",
        "description": "LAN-Based Data Acquisition Unit ensures seamless communication among PCs for Aeronautical Development Establishment's onboard data acquisition via Ethernet in the LAN.",
        "detailDescription" : "The LAN Based Data Acquisition Unit builds a close communication among the personal computers to improve the reliable acquiring, monitoring and measurement of On Board data for Aeronautical Development Establishment. Data acquisition is accomplished through the Ethernet within the LAN (Local Area Network).The unit is equipped with analog and digital I/O modules with specified channels for the input and output signals. All the I/O s are connected via Mill D38999 series connectors along with ESD protection for the I/O’s."
    },{
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "VARUNASTRA PORTABLE PRESETTER",
        "description": "Varunastra Portable Presetter: Electronic Sub-System for Varunasatra Torpedo, setting parameters before firing. Rugged, portable, 12.1-inch TFT LCD for monitoring.",
        "detailDescription" : "The Varunastra Portable Presetter is an Electronic Sub-System for Varunasatra Torpedo. The design and development of this system is intended to set the required parameters in the Torpedo before firing. It is a rugged portable unit with a 12.1inch TFT LCD display to monitor all the Presetting parameters of the Torpedo."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "PRESETTER CONVERTER BOX",
        "description": "The Presetter Converter Box is a communication interface between the MDAC system and a PC. RS-422 lines are converted to RS-232 and vice-versa for the communication with the MDAC system.",
        "detailDescription" : "The Presetter Converter Box is a communication interface between the MDAC system and a PC. RS-422 lines are converted to RS-232 and vice-versa for the communication with the MDAC system."
    },{
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "VARUNASTRA TORPEDO SIMULATOR",
        "description": "Varunastra Torpedo Simulator: Electronic Sub-System for testing Presetter parameters and load systems without actual Torpedo.",
        "detailDescription" : "The Varunastra Torpedo Simulator is an Electronic Sub-System for Varunasatra Torpedo. The design and development of is intended to test the Presetter parameters and actual load system testing instead of the actual Torpedo."
    },{
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Blast Pressure Data Controller and Recorder",
        "description": "Designed for pressure measurement and explosion trials. Rugged system integrates pressure sensor, records peak pressure, and time of arrival.",
        "detailDescription" : "It is intended for the Pressure measurement, Explosion Characterization and Instant Data Recording during the explosion trials in air. The ruggedized system is integrated with the pressure sensor to measure and store the peak pressure and the time of arrival measurements often used to study the blast effects. The system includes a Controller which synchronizes the Recorders which are connected to the sensors. "
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Miniature battery operated high speed recorder",
        "description": "For explosion trials, our ruggedized system measures and records peak pressure, time of arrival with synchronized controllers and recorders.",
        "detailDescription" : "It is intended for the Pressure measurement, Explosion Characterization and Instant Data Recording during the explosion trials in air. The ruggedized system is integrated with the pressure sensor to measure and store the peak pressure and the time of arrival measurements often used to study the blast effects. The system includes a Controller which synchronizes the Recorders which are connected to the sensors."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "High-g Shock Data Logging Module",
        "description": "High-'g' Shock Data Logging Module: Real-time impact acceleration measurement up to 20000g, fitted in ammunition for dynamic field launch.",
        "detailDescription" : "The single channel high ‘g’ shock data logging module is designed to acquire real time measurement of impact/shock acceleration (g) data values of the order up to 20000g. This module is interfaced to a high g shock sensor. This module will be fitted in the ammunition and further will be launched in the dynamic field condition."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "HIGH SPEED RECORDER",
        "description": "Designed for pressure measurement, explosion characterization, and instant data recording in air explosion trials. Integrated, rugged system with synchronized recorders.",
        "detailDescription" : "It is intended for the Pressure measurement, Explosion Characterization and Instant Data Recording during the explosion trials in air. The ruggedized system is integrated with the pressure sensor to measure and store the peak pressure and the time of arrival measurements often used to study the blast effects. The system includes a Controller which synchronizes the Recorders which are connected to the sensors."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "4-Channel Data Logging Module",
        "description": "Logs 4-channel data simultaneously, stores in-memory, retrievable through serial interface.",
        "detailDescription" : "It is a microcontroller based real time measurement and recording system. It has a provision of logging 4 channel data simultaneously. The recorded data is stored in built-in memory and is retrievable using serial interface after its operation. "
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "PULSE GENERATION MODULE",
        "description": "Highly efficient Pulse Generating Module: Generates peak current up to 250A on 2Ω load, <2µs rise time. Input: 3.5V to 9V.",
        "detailDescription" : "The Pulse Generating Module is a high voltage high current pulse discharge system capable of generating peak current up to 250A on 2Ω load, with less than 2µs rise time. It is capable of working on an input voltage range of 3.5V to 9V."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Electronic Safe and Arm Device  (ESAD)",
        "description": "Master/Slave microcontroller Module ensures safe, reliable command initiation based on time or impact. Inductive Fuze Setter enables programmability.",
        "detailDescription" : "It is a Master / Slave microcontroller based Module which provides a safe and reliable operation for initiation of commands on time or impact basis. The programmability of the Module is done by inductive sensing coils using an Inductive Fuze Setter. The Module is designed to meet the safety arming and disarming features. "
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Release Sensing and Arming System  (RSAS)",
        "description": "Release Sensing and Arming System: Microcontroller-based, senses armament store release, generates arming command sequence.",
        "detailDescription" : "The Release Sensing and Arming System is a Microcontroller based system intended for sensing the mechanical release of armament store from the carrier through different electrical and mechanical devices of the armament system and to generate necessary command sequence for system arming"
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Terminal Event Sequencer (TES) module Geometry-I",
        "description": "Microcontroller-based, acquires, stores, and processes terminal event data, generates prescribed commands.",
        "detailDescription" : "The TES Module is an embedded system designed and developed using microcontroller. It has own battery and sensing elements. TES after getting armed will acquire the terminal event data from the master controller through RS232 interface. It stores the data in built-in EEPROM. Further it processes the information and generates two commands in a prescribed sequence and timing. TES has proper interfaces for sensing the impact and mishandling (Tilt Sending) of the armament store."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Inductively Settable Control Unit (ISCU)-ESAD",
        "description": "Microcontroller-based Inductive Control Module for safe charge and fire commands, inductively settable with impact sensing.",
        "detailDescription" : "Inductive Settable Control Unit Module is a microcontroller based system which provides a safe and reliable operation for the initiation of charge and fire commands on the basis of time delays. The charge and the fire command delays are inductively settable through the Setter Device and are stored in the internal memory of the microcontroller. It also senses the impact through on-board g-sensor for impact based fire command initiation."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "ISCU Module VER2",
        "description": "ISCU Ver2.0: Microcontroller-based module for safe charge and fire commands with inductive and impact settings.",
        "detailDescription" : "Inductive Settable Control Unit (ISCU- Ver2.0) Module is a microcontroller based system which provides a safe and reliable operation for the initiation of charge and fire commands on the basis of time delays. The fire command delay which is inductive settable through the Setter Device is stored in the internal memory of the microcontroller and also senses the impact through on-board g-sensor for impact based fire command initiation."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Inductive Fuze Setter",
        "description": "Programs fuze delay wirelessly, conforms to STANAG 4369, rugged handheld, battery-operated unit.",
        "detailDescription" : "The Inductive Fuze Setter is designed to program the delay time of the Fuze wirelessly. The product is designed as per the International STANAG 4369 Protocol. The Fuze can be programmed and the programmed value can be read back from the Fuze to check for the validity It’s a Rugged handheld battery operated unit."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Earth Magnetic Filed Simulator and Calibration unit",
        "description": "Enhance magnetic sensor accuracy for Defense and Aerospace, especially in detecting underwater sea mines.",
        "detailDescription" : "Magnetic Sensors Play a vital role in the field of Defence and Aerospace applications and also they establish their mark in the field of under water sea mines. When a ship or a submarine pass any deployed sea mine, the sea mine detects the incoming target by sensing the magnetic field generated by the target. The magnetic signature is one of the parameter to detect and analyse the target. \nThe Tri-Axial Magnetic Sensor Calibration Unit is designed and developed to calibrate such type of magnetic sensors. The performance of the magnetic sensor with reference to the reading accuracy is the key.  The Calibration Unit consists of Coil System, Controller Electronic Unit, Graphical User Interface and Data Acquisition system. The sensor is calibrated over its entire range and the data is captured and analysed by the software to check for its performance analysis."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Pinger Test Panel",
        "description": "Test Acoustic Pinger Unit with Panel: Battery-operated, mounted atop Torpedo Exercise head for specified signals.",
        "detailDescription" : "Pinger test panel is used for testing the Acoustic pinger unit. Acoustic pinger is a battery operated device, which is mounted on top portion of Exercise head of Torpedo. Once the circuit is powered by shorting the wires, the pinger starts working and pings at a designed frequency with specified pulse width and repetition rate."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "RPM Test Panel",
        "description": "Simultaneous RPM, DC Voltage, Current measurement for dual motors, with water leakage detection.",
        "detailDescription" : "This instrument is a custom build Portable Test Panel made for simultaneous measurement of RPM of two motors or Inner & Outer RPM of contra rotating propulsion motor DC Voltage applied to the CR propulsion motor, Current drawn by the motor, and also indicates any water leakage into CR Propulsion motor."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Frequency Measurement Test Panel",
        "description": "Measures burst signal frequency with time display and +/-4 Hz resolution accuracy.",
        "detailDescription" : "The purpose of Frequency measuring test panel is to measure the frequency in a burst signal at any point of time of the pulse duration. The measurement system displays the frequency of the signal in the burst and also the time at which point the measurement is done with frequency resolution of +/-4 Hz."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "Exercise Head Simulator",
        "description": "Simulates torpedo prep, receives commands, and acknowledges to Presetter during preparation.",
        "detailDescription" : "The TAL Exercise head simulator is used for simulating the function of TAL Exercise head during Torpedo preparation stage. This simulator will be connected in place of Exercise head during Torpedo preparation for receiving certain commands and acknowledging to Presetter."
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "MCCS Test Panel",
        "description": "Monitors and simulates MCCS commands for validation, ensuring proper functionality before operation.",
        "detailDescription" : "The Test System is designed to monitor and simulates commands of MCCS for the purpose of validating the MCCS. This Rugged Test System is a standalone unit used to monitor the MCCS outputs and also to simulate certain commands to MCCS for its validation before its operation. "
    }, {
        "type": "defense",
        "typeTitle": "Defense",
        "productName": "UDAC Test System (Under Water Mine Test System)",
        "description": "Simulates sensor inputs for underwater mine testing, aiding validation and recovery operations.",
        "detailDescription" : "UDAC Test System is designed for the purpose of testing the underwater mines, this Test System is having the facility to simulate different sensor inputs within the range to which the UDAC sensors will respond. The test system is capable of generating input signatures for the sensors like ELFE sensor, Mag. sensor, Inclinometer, Depth sensor, Seismic sensor, Low and High frequencies. Also the test system helps in the recovery of mines by receiving the inputs from Smoke marker, Flasher, HE Bolt and pings with Acoustic sensor."
    }, {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "Remote Monitoring System",
        "description": "Uses GSM for equipment surveillance, dual GPRS modems, GPS timestamping, and global access.",
        "detailDescription" : "Remote Monitoring system Monitoring and Control plays a vital role in every manufacturing and process sectors. The Remote Monitoring System provides the communication interface for equipment which are located in remote and inaccessible locations. It provides us the control and visibility for all unattended equipment which are to be monitored continuously.\n The Remote Monitoring System is designed to monitor and control the parameters of equipment under surveillance. It uses GSM as the communication media between the RMS and the control station. The RMS is equipped with dual redundant GPRS Modems to prevent any loss of data transmission. The control station has a Graphical User Interface to monitor all the required parameters of the equipment in the real time. The GUI has the provision to Add or to Modify one location or multiple locations globally. The real time data can be time stamped using the inbuilt GPS. The data can be directly uploaded to a website also from the RMS, if they are to be monitored from any location globally."
    },  {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "Vehicle Tracking System",
        "description": "Enhances logistics by monitoring fleet, ensuring efficiency, security, and improved business processes.",
        "detailDescription" : "Logistics and Fleet management plays a significant part in the transportation of various cargo or even public transport. Greater visibility of the fleet ensures us to monitor conditions like vehicles from being idle, delivery schedules, vehicles usage and prescribed routes.\n The Vehicle Tracking System consists of a Tracking device installed in a vehicle and Tracking Software to monitor at the Center Location. The Tracking Device consists of an inbuilt GPS which provides us with the location information. The location information is securely transmitted to the Central Location using the GPRS Technology.The Tracking software receives this information and can be displayed in the text format, on a website or on a map. Database linked with the Tracking software ensures us to store all the vehicle related data. Real time monitoring can be done with this system and it can also provide us with a complete record of the vehicle usage whenever required.\n The Vehicle Tracking System ensures us to improve business process, customer service, enhanced efficiency and moreover providing us the security of our vehicles."
    },  {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "Voltage Sensor Module",
        "description": "Continuously senses and monitors various voltages, providing reliable output monitoring.",
        "detailDescription" : "The Voltage Sensor Module consists on a Voltage Sensing Module. This module is designed to continuously sense the different voltages and to monitor the output of this module."
    },  {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "Distant Indicating Wind Equipment",
        "description": "Automatic Weather Station display and store wind direction/speed data with various averages.",
        "detailDescription" : "The Distant Indicating Wind Equipment is design and developed for Automatic Weather Station  to indicate the Wind Direction and Speed. The wind direction and wind speed data is acquired through sensors and stored in the Data acquisition unit. The unit is capable to  display and store the  instantaneous values, one minute average, two minute average and ten minute average values of speed and direction."
    }, {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "Automatic Data Hosting System",
        "description": "Logs and hosts data using GPRS, ideal for remote, battery-operated equipment monitoring.",
        "detailDescription" : "The Automatic Data Hosting System is a low power data logging and data hosting device. This device is capable of storing the data for a prescribed time and hosts the stored data at some predefined selectable time interval using GPRS communication to any server or website. Data can be uploaded to a server or website by sending an SMS to the Automatic Data Hosting System. Internal memory is provided to store the data in case of GPRS communication failure as a backup option.\n Being a low power device , it is ideal for monitoring battery or solar operated equipment installed in a remote location."
    },  {
        "type": "industrial",
        "typeTitle": "Industrial",
        "productName": "GPS based Digital Time Zone Display",
        "description": "Captures GPS from 12 satellites, shows UTC, city names, time zones, date.",
        "detailDescription" : "Digital Time Zonal Display is a GPS based LED time zone display. It has the capability of capturing the GPS information from 12 satellites simultaneously giving us the required accurate GPS time signal. It has provision to display UTC with three city names with time zones, current date and day of the location."
    }
]